# Generated by Django 2.1.7 on 2021-04-19 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import virtualrooms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload the support material file.', upload_to=virtualrooms.models.materialfile_upload_to, verbose_name='file')),
                ('file_type', models.CharField(blank=True, max_length=25)),
                ('file_name', models.CharField(blank=True, max_length=30, verbose_name='material (file) name')),
                ('file_description', models.TextField(blank=True, help_text='Describe or explain what the support material consists of (you can leave blank).', max_length=80, verbose_name='material (file) description')),
                ('active', models.BooleanField(default=False, verbose_name='active material?')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='VirtualRoomPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name or title of the activity, event, or session.', max_length=150, verbose_name='activity / event name')),
                ('facilitator', models.CharField(blank=True, help_text='Name of Facilitator/Exhibitor (you can leave blank).', max_length=150, verbose_name='facilitator / exhibitor')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('date', models.DateField(help_text='Scheduled date.', verbose_name='date')),
                ('hour_from', models.TimeField(help_text='Time at which the session is scheduled to begin.', verbose_name='start time')),
                ('clock', models.BooleanField(default=True, help_text='Countdown to the start of the activity.', verbose_name='date/time countdown')),
                ('datetime_from', models.DateTimeField(blank=True, null=True)),
                ('online_room_url', models.URLField(help_text='Web link (URL) to the virtual room where the online activity takes place.', max_length=250, verbose_name='online room link')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
        migrations.AddField(
            model_name='sessionmaterial',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='virtualrooms.VirtualRoomPage'),
        ),
    ]
