# Generated by Django 2.1.7 on 2021-05-05 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0001_initial'),
        ('virtualrooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendeeVRoom',
            fields=[
                ('attendee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attendees.Attendee')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendees', to='virtualrooms.VirtualRoomPage')),
            ],
            bases=('attendees.attendee',),
        ),
    ]
