# Generated by Django 2.1.7 on 2021-05-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualrooms', '0002_attendeevroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualroompage',
            name='attendee_info',
            field=models.BooleanField(default=True, help_text='Requests the e-mail address and name of the attendee to access the page.', verbose_name='Attendee info?'),
        ),
        migrations.AlterField(
            model_name='virtualroompage',
            name='clock',
            field=models.BooleanField(default=True, help_text='Countdown to the start of the activity.', verbose_name='date/time countdown?'),
        ),
    ]
