# Generated by Django 2.1.7 on 2021-04-19 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import landings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A catchy title or name for the page.', max_length=100, verbose_name='landing page header')),
                ('title_form', models.CharField(default='DO YOU WANT MORE INFORMATION?', help_text='Title for the contact form.', max_length=100, verbose_name='form title')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('clock', models.DateTimeField(blank=True, help_text='Use this field only if you want a countdown to be displayed.', null=True, verbose_name='date/time countdown')),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('MXN', 'Mexican peso'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(blank=True, decimal_places=4, default=None, default_currency='USD', help_text='Use this field only if you want a price to be displayed.', max_digits=19, null=True, verbose_name='price to show')),
                ('file', models.FileField(help_text='Upload main file to show in the Landing Page (pdf, ppt, image, video, mp3, etc.).', upload_to=landings.models.landingfile_upload_to, verbose_name='file')),
                ('file_type', models.CharField(max_length=25, null=True)),
                ('newsletter_popup', models.CharField(choices=[('NO', 'No'), ('YNL', 'Yes. Newsletter')], default='NO', help_text='A pop-up window for visitors to subscribe to your mailing list.', max_length=4, verbose_name='Newsletter subscription pop-up window?')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
