# Generated by Django 2.1.7 on 2021-04-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=240, null=True, verbose_name='name')),
                ('phone_number', models.CharField(blank=True, max_length=60, null=True, verbose_name='phone number (cell)')),
                ('obj_interest_id', models.IntegerField(blank=True, null=True, verbose_name='product ID.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
